In [1]:
import pandas as pd

In [2]:
# Load the dataset
df = pd.read_csv('population.csv')
df

            Entity Code   Year  Population (historical)
0      Afghanistan  AFG -10000                    14737
1      Afghanistan  AFG  -9000                    20405
2      Afghanistan  AFG  -8000                    28253
3      Afghanistan  AFG  -7000                    39120
4      Afghanistan  AFG  -6000                    54166
...            ...  ...    ...                      ...
59172     Zimbabwe  ZWE   2019                 15271377
59173     Zimbabwe  ZWE   2020                 15526888
59174     Zimbabwe  ZWE   2021                 15797220
59175     Zimbabwe  ZWE   2022                 16069061
59176     Zimbabwe  ZWE   2023                 16340829

[59177 rows x 4 columns]

In [5]:
# Filter the rows where 'Year' is greater than 1900
df_filtered = df[df['Year'] >= 1920]
df_filtered

            Entity Code  Year  Population (historical)
157    Afghanistan  AFG  1920                 10188845
158    Afghanistan  AFG  1921                 10162753
159    Afghanistan  AFG  1922                  9893152
160    Afghanistan  AFG  1923                  9374030
161    Afghanistan  AFG  1924                  8882148
...            ...  ...   ...                      ...
59172     Zimbabwe  ZWE  2019                 15271377
59173     Zimbabwe  ZWE  2020                 15526888
59174     Zimbabwe  ZWE  2021                 15797220
59175     Zimbabwe  ZWE  2022                 16069061
59176     Zimbabwe  ZWE  2023                 16340829

[26007 rows x 4 columns]

In [6]:
# Save the filtered dataset if needed
df_filtered.to_csv('cleaned_population.csv', index=False)

# Display the first few rows to check
print(df_filtered.head())

          Entity Code  Year  Population (historical)
157  Afghanistan  AFG  1920                 10188845
158  Afghanistan  AFG  1921                 10162753
159  Afghanistan  AFG  1922                  9893152
160  Afghanistan  AFG  1923                  9374030
161  Afghanistan  AFG  1924                  8882148

In [7]:
# Load the dataset
df = pd.read_csv('temperature-anomaly.csv')
df

,Entity,Code,Year,Global average temperature anomaly relative to 1961-1990,Upper bound of the annual temperature anomaly (95% confidence interval),Lower bound of the annual temperature anomaly (95% confidence interval)
0,Global,NaN,1850,-0.417711,-0.246166,-0.589256
1,Global,NaN,1851,-0.233350,-0.054832,-0.411868
2,Global,NaN,1852,-0.229399,-0.049416,-0.409382
3,Global,NaN,1853,-0.270354,-0.110700,-0.430009
4,Global,NaN,1854,-0.291521,-0.150330,-0.432712
...,...,...,...,...,...,...
520,Southern hemisphere,NaN,2020,0.569932,0.622113,0.517750
521,Southern hemisphere,NaN,2021,0.445618,0.499061,0.392176
522,Southern hemisphere,NaN,2022,0.502809,0.557299,0.448319
523,Southern hemisphere,NaN,2023,0.786759,0.843433,0.730086
524,Southern hemisphere,NaN,2024,0.810510,0.864169,0.756850

In [8]:
# Filter the rows where 'Year' is greater than 1900
df_filtered = df[df['Year'] >= 1920]
df_filtered

,Entity,Code,Year,Global average temperature anomaly relative to 1961-1990,Upper bound of the annual temperature anomaly (95% confidence interval),Lower bound of the annual temperature anomaly (95% confidence interval)
70,Global,NaN,1920,-0.298355,-0.165629,-0.431081
71,Global,NaN,1921,-0.240444,-0.116380,-0.364509
72,Global,NaN,1922,-0.339014,-0.228344,-0.449683
73,Global,NaN,1923,-0.317682,-0.209300,-0.426064
74,Global,NaN,1924,-0.311802,-0.203192,-0.420411
...,...,...,...,...,...,...
520,Southern hemisphere,NaN,2020,0.569932,0.622113,0.517750
521,Southern hemisphere,NaN,2021,0.445618,0.499061,0.392176
522,Southern hemisphere,NaN,2022,0.502809,0.557299,0.448319
523,Southern hemisphere,NaN,2023,0.786759,0.843433,0.730086
524,Southern hemisphere,NaN,2024,0.810510,0.864169,0.756850

In [9]:

df_filtered.to_csv('cleaned_temperature-anomaly.csv', index=False)

In [10]:
# Load the dataset
df = pd.read_csv('annual-co-emissions.csv')
df

            Entity  Year  Annual CO₂ emissions
0      Afghanistan  1949               14656.0
1      Afghanistan  1950               84272.0
2      Afghanistan  1951               91600.0
3      Afghanistan  1952               91600.0
4      Afghanistan  1953              106256.0
...            ...   ...                   ...
29132     Zimbabwe  2019            10262950.0
29133     Zimbabwe  2020             8494503.0
29134     Zimbabwe  2021            10203630.0
29135     Zimbabwe  2022            10424940.0
29136     Zimbabwe  2023            11164030.0

[29137 rows x 3 columns]

In [11]:
# Filter the rows where 'Year' is greater than 1920
df_filtered = df[df['Year'] >= 1920]
df_filtered

            Entity  Year  Annual CO₂ emissions
0      Afghanistan  1949               14656.0
1      Afghanistan  1950               84272.0
2      Afghanistan  1951               91600.0
3      Afghanistan  1952               91600.0
4      Afghanistan  1953              106256.0
...            ...   ...                   ...
29132     Zimbabwe  2019            10262950.0
29133     Zimbabwe  2020             8494503.0
29134     Zimbabwe  2021            10203630.0
29135     Zimbabwe  2022            10424940.0
29136     Zimbabwe  2023            11164030.0

[21083 rows x 3 columns]

In [12]:

df_filtered.to_csv('cleaned_annual-co-emissions.csv', index=False)

In [13]:
# 2023 population every country

In [14]:
df = pd.read_csv('cleaned_population.csv')
df

            Entity Code  Year  Population (historical)
0      Afghanistan  AFG  1920                 10188845
1      Afghanistan  AFG  1921                 10162753
2      Afghanistan  AFG  1922                  9893152
3      Afghanistan  AFG  1923                  9374030
4      Afghanistan  AFG  1924                  8882148
...            ...  ...   ...                      ...
26002     Zimbabwe  ZWE  2019                 15271377
26003     Zimbabwe  ZWE  2020                 15526888
26004     Zimbabwe  ZWE  2021                 15797220
26005     Zimbabwe  ZWE  2022                 16069061
26006     Zimbabwe  ZWE  2023                 16340829

[26007 rows x 4 columns]

In [15]:
df_filtered = df[df['Year'] == 2023]
df_filtered

               Entity      Code  Year  Population (historical)
103       Afghanistan       AFG  2023                 41454762
207            Africa       NaN  2023               1480770740
281       Africa (UN)       NaN  2023               1480770527
387           Albania       ALB  2023                  2811660
491           Algeria       DZA  2023                 46164221
...               ...       ...   ...                      ...
25508  Western Sahara       ESH  2023                   579735
25585           World  OWID_WRL  2023               8091734935
25689           Yemen       YEM  2023                 39390800
25902          Zambia       ZMB  2023                 20723968
26006        Zimbabwe       ZWE  2023                 16340829

[260 rows x 4 columns]

In [16]:
df_filtered.to_csv('cleaned_population_2023.csv', index=False)

In [17]:
df = pd.read_csv('cleaned_population_2023.csv')
df

             Entity      Code  Year  Population (historical)
0       Afghanistan       AFG  2023                 41454762
1            Africa       NaN  2023               1480770740
2       Africa (UN)       NaN  2023               1480770527
3           Albania       ALB  2023                  2811660
4           Algeria       DZA  2023                 46164221
..              ...       ...   ...                      ...
255  Western Sahara       ESH  2023                   579735
256           World  OWID_WRL  2023               8091734935
257           Yemen       YEM  2023                 39390800
258          Zambia       ZMB  2023                 20723968
259        Zimbabwe       ZWE  2023                 16340829

[260 rows x 4 columns]

In [20]:
df_filtered = df.dropna(subset=['Code'])
df_filtered

             Entity      Code  Year  Population (historical)
0       Afghanistan       AFG  2023                 41454762
3           Albania       ALB  2023                  2811660
4           Algeria       DZA  2023                 46164221
5    American Samoa       ASM  2023                    47543
7           Andorra       AND  2023                    80868
..              ...       ...   ...                      ...
255  Western Sahara       ESH  2023                   579735
256           World  OWID_WRL  2023               8091734935
257           Yemen       YEM  2023                 39390800
258          Zambia       ZMB  2023                 20723968
259        Zimbabwe       ZWE  2023                 16340829

[239 rows x 4 columns]

In [21]:
df_filtered.to_csv('cleaned_population_2023.csv', index=False)

In [31]:
import pandas as pd

# Load the dataset
df = pd.read_csv("cleaned_annual-co-emissions-country.csv")

# Display column names to check for inconsistencies
print(df.columns)

Index(['Entity', 'Year', 'Annual CO2 emissions'], dtype='object')

In [32]:
# Rename columns if necessary (fix spacing, encoding issues)
df.rename(columns=lambda x: x.strip(), inplace=True)

# Convert "Annual CO₂ emissions" to numeric (handle missing or incorrect values)
df["Annual CO2 emissions"] = pd.to_numeric(df["Annual CO2 emissions"], errors="coerce")
df

            Entity  Year  Annual CO2 emissions
0      Afghanistan  1949               14656.0
1      Afghanistan  1950               84272.0
2      Afghanistan  1951               91600.0
3      Afghanistan  1952               91600.0
4      Afghanistan  1953              106256.0
...            ...   ...                   ...
18076     Zimbabwe  2019            10262950.0
18077     Zimbabwe  2020             8494503.0
18078     Zimbabwe  2021            10203630.0
18079     Zimbabwe  2022            10424940.0
18080     Zimbabwe  2023            11164030.0

[18081 rows x 3 columns]

In [33]:
df = df[df['Entity'] != 'World']
df

            Entity  Year  Annual CO2 emissions
0      Afghanistan  1949               14656.0
1      Afghanistan  1950               84272.0
2      Afghanistan  1951               91600.0
3      Afghanistan  1952               91600.0
4      Afghanistan  1953              106256.0
...            ...   ...                   ...
18076     Zimbabwe  2019            10262950.0
18077     Zimbabwe  2020             8494503.0
18078     Zimbabwe  2021            10203630.0
18079     Zimbabwe  2022            10424940.0
18080     Zimbabwe  2023            11164030.0

[17977 rows x 3 columns]

In [34]:

df.to_csv("cleaned_annual-co-emissions-country.csv", index=False)