In [15]:
import pandas as pd
dm = pd.read_csv("cleaned_annual-co-emissions.csv")

In [12]:
dm = dm[dm['Entity'].isin(["Asia", "Africa", "Europe", "South America", "North America","Oceania"])]

In [13]:
dm = dm.reset_index(drop = True)

In [14]:
dm.to_csv("cleaned_annual-co-emissions-continent.csv", index = False)

In [64]:
df = pd.read_csv("cleaned_population_2023.csv")

In [65]:
name_list = df['Entity'].tolist()

In [21]:
dm = dm[dm['Entity'].isin(name_list)]

In [22]:
dm.to_csv("cleaned_annual-co-emissions-country.csv", index = False)

In [23]:
dm = dm[dm['Year']==2023]

In [24]:
dm.to_csv("co-emission-country-2023.csv",index = False)

In [25]:
merged_df = pd.merge(df, dm, on='Entity', how='inner')

In [31]:
merged_df = merged_df.drop(columns = ["Annual CO₂ emissions", "Population (historical)"])

In [29]:
merged_df["Per capita CO2 emissions"] = merged_df["Annual CO₂ emissions"]/merged_df["Population (historical)"]

In [33]:
merged_df.to_csv("Per capita CO2 emissions 2023.csv",index=False)

In [12]:
import pandas as pd
dk = pd.read_csv("contribution-to-global-mean-surface-temperature-rise-from-fossil-sources.csv")
dk

,Entity,Year,Change in global mean surface temperature caused by greenhouse gas emissions from fossil fuels and industry
0,Afghanistan,1851,2.051104e-07
1,Afghanistan,1852,4.119043e-07
2,Afghanistan,1853,6.203892e-07
3,Afghanistan,1854,8.305728e-07
4,Afghanistan,1855,1.042461e-06
...,...,...,...
40823,Zimbabwe,2019,6.302008e-04
40824,Zimbabwe,2020,6.369070e-04
40825,Zimbabwe,2021,6.445837e-04
40826,Zimbabwe,2022,6.525368e-04
40827,Zimbabwe,2023,6.610378e-04

In [13]:
dk = dk[dk['Entity'].isin(name_list)]

In [14]:
dk = dk[dk['Year']>1920]

In [16]:
dk.to_csv("tep_country.csv",index = False)

In [60]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Load your data into a DataFrame
df = pd.read_csv("cleaned_annual-co-emissions-country.csv")

# Prepare the time series data
df = df[['Entity', 'Year', 'Annual CO_ emissions']]

# Initialize an empty dictionary to store forecasts
forecast_dict = {}

# Loop through each unique country (Entity)
for country in df['Entity'].unique():
    country_data = df[df['Entity'] == country]
    
    # Set Year as the independent variable (X) and 'Change in global mean surface temperature' as the dependent variable (y)
    X = country_data[['Year']]  # We only use the Year to predict the temperature change
    y = country_data['Annual CO_ emissions']
    
    # Instantiate and fit the linear regression model
    model = LinearRegression()
    model.fit(X, y)
    
    # Make predictions for the next 7 years (2024-2030)
    future_years = np.array(range(2024, 2031)).reshape(-1, 1)
    forecast = model.predict(future_years)
    
    # Store the forecast in the dictionary
    forecast_dict[country] = forecast[6]
    

# Print the forecast
forecast_df = pd.DataFrame(list(forecast_dict.items()), columns=['Country', 'Forecast'])
print(forecast_dict)

/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

{'Afghanistan': np.float64(8746109.577101558), 'Albania': np.float64(6496579.43954134), 'Algeria': np.float64(153035304.5158019), 'Andorra': np.float64(482531.14746982424), 'Angola': np.float64(26048253.45908916), 'Anguilla': np.float64(180571.38179679122), 'Antigua and Barbuda': np.float64(648585.5742064416), 'Argentina': np.float64(206158396.01112747), 'Armenia': np.float64(7683071.57887283), 'Aruba': np.float64(1772241.0516229048), 'Australia': np.float64(453506439.8045254), 'Austria': np.float64(83880278.00473714), 'Azerbaijan': np.float64(51110388.1161474), 'Bahamas': np.float64(2783304.5300972983), 'Bahrain': np.float64(32584035.070904374), 'Bangladesh': np.float64(78133887.05287552), 'Barbados': np.float64(1725934.1377250329), 'Belarus': np.float64(96133926.33161211), 'Belgium': np.float64(128843370.33146274), 'Belize': np.float64(679313.4246560521), 'Benin': np.float64(5126027.361086696), 'Bermuda': np.float64(738558.4444500543), 'Bhutan': np.float64(1662801.3096985891), 'Bolivia': np.float64(17899998.141794622), 'Bonaire Sint Eustatius and Saba': np.float64(119045.56823954242), 'Bosnia and Herzegovina': np.float64(23249366.567769825), 'Botswana': np.float64(7671960.073952019), 'Brazil': np.float64(486564513.9560528), 'British Virgin Islands': np.float64(245637.88569917716), 'Brunei': np.float64(10097769.414008617), 'Bulgaria': np.float64(77734780.45906854), 'Burkina Faso': np.float64(3939088.1185238063), 'Burundi': np.float64(543767.4288630877), 'Cambodia': np.float64(11268815.7963866), 'Cameroon': np.float64(10539160.200219631), 'Canada': np.float64(682164375.1321983), 'Cape Verde': np.float64(601508.4539539404), 'Central African Republic': np.float64(261270.79455232807), 'Chad': np.float64(2077675.2592254728), 'Chile': np.float64(78541520.90135479), 'China': np.float64(8434242346.029999), 'Colombia': np.float64(94110802.75644541), 'Comoros': np.float64(294882.39597902074), 'Congo': np.float64(6935115.721017718), 'Cook Islands': np.float64(92324.73073593061), 'Costa Rica': np.float64(7903976.083396375), "Cote d'Ivoire": np.float64(12071484.946094036), 'Croatia': np.float64(25931306.093401432), 'Cuba': np.float64(36240381.91909206), 'Curacao': np.float64(7229473.072106801), 'Cyprus': np.float64(9695411.427377999), 'Czechia': np.float64(166909136.2050357), 'Democratic Republic of Congo': np.float64(4463887.58063747), 'Denmark': np.float64(63470241.99432421), 'Djibouti': np.float64(580488.0692343581), 'Dominica': np.float64(190742.24253362883), 'Dominican Republic': np.float64(24795933.7859962), 'East Timor': np.float64(935544.90418984), 'Ecuador': np.float64(38208108.20811105), 'Egypt': np.float64(216002607.97517776), 'El Salvador': np.float64(7213344.160962343), 'Equatorial Guinea': np.float64(7030738.580747873), 'Eritrea': np.float64(755869.3274046276), 'Estonia': np.float64(28546986.095227778), 'Eswatini': np.float64(1412412.9589966685), 'Ethiopia': np.float64(11718947.851328552), 'Faroe Islands': np.float64(915453.6718596071), 'Fiji': np.float64(1337826.6189073697), 'Finland': np.float64(71697413.71319747), 'France': np.float64(464268257.124485), 'French Polynesia': np.float64(1088123.3805626594), 'Gabon': np.float64(8162335.15813458), 'Gambia': np.float64(620746.3009085543), 'Georgia': np.float64(12694943.194220126), 'Germany': np.float64(1048987664.8446064), 'Ghana': np.float64(14667879.529753447), 'Greece': np.float64(107861667.53572702), 'Greenland': np.float64(742103.0535928924), 'Grenada': np.float64(329728.3679653462), 'Guatemala': np.float64(14737266.180577159), 'Guinea': np.float64(3257205.515418589), 'Guinea-Bissau': np.float64(335249.0362236211), 'Guyana': np.float64(2775141.5447188467), 'Haiti': np.float64(2547159.8769668266), 'Honduras': np.float64(8801673.965523303), 'Hong Kong': np.float64(52355346.15818024), 'Hungary': np.float64(79765020.67000937), 'Iceland': np.float64(4065226.3346417844), 'India': np.float64(1890418302.695816), 'Indonesia': np.float64(487568628.2753639), 'Iran': np.float64(604080477.9076672), 'Iraq': np.float64(145690823.1765232), 'Ireland': np.float64(48281450.34690285), 'Israel': np.float64(73929720.70686984), 'Italy': np.float64(544169142.5001392), 'Jamaica': np.float64(11523262.604879647), 'Japan': np.float64(1536520697.0364647), 'Jordan': np.float64(27531051.482934356), 'Kazakhstan': np.float64(309917144.6067362), 'Kenya': np.float64(17858965.89485377), 'Kiribati': np.float64(65818.7504800309), 'Kosovo': np.float64(13311830.011086345), 'Kuwait': np.float64(115529753.45230293), 'Kyrgyzstan': np.float64(14437613.015387267), 'Laos': np.float64(12164526.590517223), 'Latvia': np.float64(15277623.90095219), 'Lebanon': np.float64(23666428.51080537), 'Lesotho': np.float64(3385091.8848281205), 'Liberia': np.float64(830542.9244454652), 'Libya': np.float64(76390824.52654576), 'Liechtenstein': np.float64(239808.02806643303), 'Lithuania': np.float64(26148520.15508908), 'Luxembourg': np.float64(11119446.373661146), 'Macao': np.float64(1854306.8697176129), 'Madagascar': np.float64(3348261.5804338753), 'Malawi': np.float64(1470714.6455922984), 'Malaysia': np.float64(211854668.04733372), 'Maldives': np.float64(1840982.535723269), 'Mali': np.float64(4541397.622644216), 'Malta': np.float64(3016533.1470741183), 'Marshall Islands': np.float64(178493.75255315285), 'Mauritania': np.float64(3718766.17242527), 'Mauritius': np.float64(4666726.94259505), 'Mexico': np.float64(526187780.58161354), 'Micronesia (country)': np.float64(122573.71315982426), 'Moldova': np.float64(18126938.880713195), 'Mongolia': np.float64(32112276.787247777), 'Montenegro': np.float64(2614177.999291979), 'Montserrat': np.float64(46667.06459167483), 'Morocco': np.float64(60045882.412466764), 'Mozambique': np.float64(5019470.435871556), 'Myanmar': np.float64(19179826.85577792), 'Namibia': np.float64(5103861.823061496), 'Nauru': np.float64(57624.66922293231), 'Nepal': np.float64(9726749.721368074), 'Netherlands': np.float64(211454737.082407), 'New Caledonia': np.float64(4752328.346612379), 'New Zealand': np.float64(40539068.06791425), 'Nicaragua': np.float64(5250056.6015165895), 'Niger': np.float64(2091652.4099104032), 'Nigeria': np.float64(128124198.63151217), 'Niue': np.float64(8580.993748808833), 'North Korea': np.float64(108509943.45657372), 'North Macedonia': np.float64(11171228.036301076), 'Norway': np.float64(52445134.54532921), 'Oman': np.float64(76613874.73105049), 'Pakistan': np.float64(204602453.99218082), 'Palau': np.float64(283014.8961505303), 'Palestine': np.float64(4192795.1236608326), 'Panama': np.float64(9742234.462770164), 'Papua New Guinea': np.float64(7393971.906770229), 'Paraguay': np.float64(6108653.649048567), 'Peru': np.float64(46712137.668922424), 'Philippines': np.float64(109788053.81095886), 'Poland': np.float64(456546343.60002136), 'Portugal': np.float64(64255765.86820698), 'Qatar': np.float64(96435648.30813313), 'Romania': np.float64(152823757.424016), 'Russia': np.float64(2410535677.349655), 'Rwanda': np.float64(1194181.3739133663), 'Saint Helena': np.float64(14587.519667170884), 'Saint Kitts and Nevis': np.float64(275771.27780407295), 'Saint Lucia': np.float64(575858.9501310606), 'Saint Pierre and Miquelon': np.float64(75380.44217697158), 'Saint Vincent and the Grenadines': np.float64(278399.1774219917), 'Samoa': np.float64(257032.81743058097), 'Sao Tome and Principe': np.float64(139870.46658799239), 'Saudi Arabia': np.float64(624376489.9737587), 'Senegal': np.float64(10069866.92806071), 'Serbia': np.float64(63634222.65932083), 'Seychelles': np.float64(642927.2157588564), 'Sierra Leone': np.float64(936877.8160814531), 'Singapore': np.float64(63726118.70277953), 'Sint Maarten (Dutch part)': np.float64(914187.0489354096), 'Slovakia': np.float64(55575908.88322306), 'Slovenia': np.float64(19975646.280436873), 'Solomon Islands': np.float64(385559.68132934533), 'Somalia': np.float64(853462.5111731924), 'South Africa': np.float64(515698170.7270889), 'South Korea': np.float64(607504034.070816), 'South Sudan': np.float64(1552377.3751431257), 'Spain': np.float64(349625189.7330475), 'Sri Lanka': np.float64(19281055.141485393), 'Sudan': np.float64(18211688.740541875), 'Suriname': np.float64(3079640.187373556), 'Sweden': np.float64(69747401.24424946), 'Switzerland': np.float64(54153343.19116616), 'Syria': np.float64(55502528.25531578), 'Taiwan': np.float64(284734286.7577238), 'Tajikistan': np.float64(8510810.235881835), 'Tanzania': np.float64(12314244.431583881), 'Thailand': np.float64(272043354.9535036), 'Togo': np.float64(2598112.7771743685), 'Tonga': np.float64(171237.87141192146), 'Trinidad and Tobago': np.float64(39996632.46423197), 'Tunisia': np.float64(31095985.753171444), 'Turkey': np.float64(359535182.0149002), 'Turkmenistan': np.float64(64141750.742498636), 'Turks and Caicos Islands': np.float64(480331.216146674), 'Tuvalu': np.float64(14915.933231474424), 'Uganda': np.float64(4491754.525558531), 'Ukraine': np.float64(516372854.59778595), 'United Arab Emirates': np.float64(237649189.0318184), 'United Kingdom': np.float64(534118706.8581031), 'United States': np.float64(6711717408.222031), 'Uruguay': np.float64(8072544.405083045), 'Uzbekistan': np.float64(149952603.6180296), 'Vanuatu': np.float64(166269.74095338816), 'Venezuela': np.float64(173078909.02158308), 'Vietnam': np.float64(168298650.93652487), 'Wallis and Futuna': np.float64(30642.221848739544), 'Yemen': np.float64(21375875.62346542), 'Zambia': np.float64(4548142.06355276), 'Zimbabwe': np.float64(14948006.387712568)}

/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [61]:
forecast_df.to_csv("forecast_cm.csv",index = False)

In [66]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

# Load your data into a DataFrame
df = pd.read_csv("cleaned_population.csv")
df = df[df['Entity'].isin(name_list)]
df = df.drop(columns = 'Code')

# Prepare the time series data
df = df[['Entity', 'Year', 'Population (historical)']]

# Initialize an empty dictionary to store forecasts
forecast_dict = {}

# Loop through each unique country (Entity)
for country in df['Entity'].unique():
    country_data = df[df['Entity'] == country]
    
    # Set Year as the independent variable (X) and 'Change in global mean surface temperature' as the dependent variable (y)
    X = country_data[['Year']]  # We only use the Year to predict the temperature change
    y = country_data['Population (historical)']
    
    # Instantiate and fit the linear regression model
    model = LinearRegression()
    model.fit(X, y)
    
    # Make predictions for the next 7 years (2024-2030)
    future_years = np.array(range(2024, 2031)).reshape(-1, 1)
    forecast = model.predict(future_years)
    
    # Store the forecast in the dictionary
    forecast_dict[country] = forecast[6]
    

# Print the forecast
forecast_df = pd.DataFrame(list(forecast_dict.items()), columns=['Country', 'Forecast'])
print(forecast_dict)

/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

{'Afghanistan': np.float64(30732122.50182444), 'Albania': np.float64(3722141.7440680712), 'Algeria': np.float64(42157972.69316125), 'American Samoa': np.float64(64973.538686536485), 'Andorra': np.float64(87594.72023364971), 'Angola': np.float64(26381990.56657952), 'Anguilla': np.float64(14850.980257489078), 'Antigua and Barbuda': np.float64(95674.76318147872), 'Argentina': np.float64(47915809.37931299), 'Armenia': np.float64(3789384.8106209263), 'Aruba': np.float64(114160.38112011831), 'Australia': np.float64(25789977.07555747), 'Austria': np.float64(8822288.105723895), 'Azerbaijan': np.float64(10650355.208433807), 'Bahamas': np.float64(428336.9483409794), 'Bahrain': np.float64(1230764.3236797191), 'Bangladesh': np.float64(174695210.98928833), 'Barbados': np.float64(304690.4675344075), 'Belarus': np.float64(10844238.971503258), 'Belgium': np.float64(11635595.36848928), 'Belize': np.float64(354700.85624133144), 'Benin': np.float64(10977423.64180091), 'Bermuda': np.float64(72279.83029602305), 'Bhutan': np.float64(771605.7649631929), 'Bolivia': np.float64(11482269.705915928), 'Bonaire Sint Eustatius and Saba': np.float64(25781.050721954904), 'Bosnia and Herzegovina': np.float64(4467064.275386758), 'Botswana': np.float64(2295540.3938600197), 'Brazil': np.float64(227647098.95417643), 'British Virgin Islands': np.float64(34860.32266376342), 'Brunei': np.float64(452834.58953376673), 'Bulgaria': np.float64(8636790.1961165), 'Burkina Faso': np.float64(18118987.085810244), 'Burundi': np.float64(10620422.786007673), 'Cambodia': np.float64(15732074.549237132), 'Cameroon': np.float64(22448782.116435528), 'Canada': np.float64(40235455.381281376), 'Cape Verde': np.float64(550450.9591166116), 'Cayman Islands': np.float64(67716.24657375691), 'Central African Republic': np.float64(4984170.58363919), 'Chad': np.float64(13806895.27428788), 'Chile': np.float64(20056012.641635537), 'China': np.float64(1554279315.107109), 'Colombia': np.float64(52190303.969593525), 'Comoros': np.float64(747999.3515256587), 'Congo': np.float64(4943914.144185439), 'Cook Islands': np.float64(17342.191002007432), 'Costa Rica': np.float64(5263863.615576655), "Cote d'Ivoire": np.float64(25592932.613298833), 'Croatia': np.float64(4795075.204518296), 'Cuba': np.float64(13556462.73419395), 'Curacao': np.float64(180398.61238059984), 'Cyprus': np.float64(1258803.308305774), 'Czechia': np.float64(10309678.598682385), 'Democratic Republic of Congo': np.float64(79047165.99540687), 'Denmark': np.float64(6172063.922122054), 'Djibouti': np.float64(1045382.8844713531), 'Dominica': np.float64(80430.76879867702), 'Dominican Republic': np.float64(11616309.19183293), 'East Timor': np.float64(1193058.7232049517), 'Ecuador': np.float64(17546898.52245277), 'Egypt': np.float64(103128848.01446152), 'El Salvador': np.float64(7293899.614360407), 'Equatorial Guinea': np.float64(1289605.7621732652), 'Eritrea': np.float64(3220182.9463832304), 'Estonia': np.float64(1504539.5630427822), 'Eswatini': np.float64(1298955.2922596782), 'Ethiopia': np.float64(99766692.32738185), 'Falkland Islands': np.float64(3482.4515186269164), 'Faroe Islands': np.float64(55710.540681246086), 'Fiji': np.float64(1067956.4655553158), 'Finland': np.float64(5915350.916659556), 'France': np.float64(68725190.95344079), 'French Guiana': np.float64(283433.948751607), 'French Polynesia': np.float64(326980.2996308133), 'Gabon': np.float64(1938105.1729702353), 'Gambia': np.float64(2181077.384700738), 'Georgia': np.float64(4954745.812941428), 'Germany': np.float64(86757175.85866857), 'Ghana': np.float64(29072464.741961002), 'Gibraltar': np.float64(35564.48303591262), 'Greece': np.float64(12058792.925861508), 'Greenland': np.float64(68063.22421469225), 'Grenada': np.float64(120024.40341939614), 'Guadeloupe': np.float64(466845.6791143976), 'Guam': np.float64(199395.74213729426), 'Guatemala': np.float64(16574028.444729567), 'Guernsey': np.float64(67229.7251684562), 'Guinea': np.float64(11923685.983399123), 'Guinea-Bissau': np.float64(1763754.9656033292), 'Guyana': np.float64(946730.5421423223), 'Haiti': np.float64(11045822.052288473), 'Honduras': np.float64(9471366.635836989), 'Hong Kong': np.float64(8645972.484087288), 'Hungary': np.float64(10728780.90927665), 'Iceland': np.float64(369322.1035580924), 'India': np.float64(1383279443.9407387), 'Indonesia': np.float64(284613996.838686), 'Iran': np.float64(89769611.59668207), 'Iraq': np.float64(36628889.4738611), 'Ireland': np.float64(4463593.72507735), 'Isle of Man': np.float64(91579.33049981482), 'Israel': np.float64(8637727.61354956), 'Italy': np.float64(65402581.111762464), 'Jamaica': np.float64(3175473.892473057), 'Japan': np.float64(147848826.95985818), 'Jersey': np.float64(109486.44793780078), 'Jordan': np.float64(8776495.763282865), 'Kazakhstan': np.float64(21349614.879083514), 'Kenya': np.float64(46540274.07282627), 'Kiribati': np.float64(119865.29821828636), 'Kosovo': np.float64(2224040.751543872), 'Kuwait': np.float64(3655688.781089291), 'Kyrgyzstan': np.float64(6654547.100666806), 'Laos': np.float64(7352793.534530029), 'Latvia': np.float64(2395406.102395177), 'Lebanon': np.float64(6009472.825925514), 'Lesotho': np.float64(2496979.6762456), 'Liberia': np.float64(4493847.443721339), 'Libya': np.float64(7252851.060002148), 'Liechtenstein': np.float64(41128.18668515945), 'Lithuania': np.float64(3574602.8969540186), 'Luxembourg': np.float64(552572.4920303002), 'Macao': np.float64(651409.2580539752), 'Madagascar': np.float64(25041592.015710056), 'Malawi': np.float64(17111372.392046273), 'Malaysia': np.float64(32301096.95707345), 'Maldives': np.float64(419693.18854688946), 'Mali': np.float64(18043094.347748876), 'Malta': np.float64(487102.74551370926), 'Marshall Islands': np.float64(38819.40731889469), 'Martinique': np.float64(434759.36641823547), 'Mauritania': np.float64(3944891.9683612436), 'Mauritius': np.float64(1476458.8998026252), 'Mayotte': np.float64(266616.46542382985), 'Mexico': np.float64(133275990.51377392), 'Micronesia (country)': np.float64(131724.68020377634), 'Moldova': np.float64(4520174.89475622), 'Monaco': np.float64(35819.952901952434), 'Mongolia': np.float64(3219722.293854691), 'Montenegro': np.float64(681993.0542729124), 'Montserrat': np.float64(3290.7650881884038), 'Morocco': np.float64(37838496.03449261), 'Mozambique': np.float64(26549702.85139233), 'Myanmar': np.float64(57285969.65945804), 'Namibia': np.float64(2480953.413666919), 'Nauru': np.float64(12883.842478395381), 'Nepal': np.float64(31052105.93345785), 'Netherlands': np.float64(19312986.39061132), 'New Caledonia': np.float64(312907.93285049126), 'New Zealand': np.float64(5085160.660130158), 'Nicaragua': np.float64(6755939.63158007), 'Niger': np.float64(19009900.954315603), 'Nigeria': np.float64(188481248.0013919), 'Niue': np.float64(731.3879748241307), 'North Korea': np.float64(29019052.163821638), 'North Macedonia': np.float64(2339322.889309723), 'Northern Mariana Islands': np.float64(71322.12738985568), 'Norway': np.float64(5420006.693630643), 'Oman': np.float64(3639639.6779953092), 'Pakistan': np.float64(219976993.26867008), 'Palau': np.float64(21013.22723781073), 'Palestine': np.float64(4484662.855473161), 'Panama': np.float64(4220089.614920512), 'Papua New Guinea': np.float64(8625153.691928953), 'Paraguay': np.float64(6707350.941048741), 'Peru': np.float64(34321343.37826204), 'Philippines': np.float64(111122135.98889899), 'Poland': np.float64(42019867.79552972), 'Portugal': np.float64(11483512.664600432), 'Puerto Rico': np.float64(4123562.6777403653), 'Qatar': np.float64(1813308.8304438218), 'Reunion': np.float64(992565.2944847364), 'Romania': np.float64(23785412.608183086), 'Russia': np.float64(167715009.01621675), 'Rwanda': np.float64(12087241.44794625), 'Saint Barthelemy': np.float64(11218.817652721249), 'Saint Helena': np.float64(6086.097137897413), 'Saint Kitts and Nevis': np.float64(47432.68418329245), 'Saint Lucia': np.float64(190470.5712738717), 'Saint Martin (French part)': np.float64(44600.33457238064), 'Saint Pierre and Miquelon': np.float64(6640.138139811399), 'Saint Vincent and the Grenadines': np.float64(132524.04921049834), 'Samoa': np.float64(236123.06742238346), 'San Marino': np.float64(34069.59270244319), 'Sao Tome and Principe': np.float64(197930.5253654113), 'Saudi Arabia': np.float64(26088436.218217254), 'Senegal': np.float64(14811922.299487889), 'Serbia': np.float64(8793242.332294896), 'Seychelles': np.float64(113202.19466019422), 'Sierra Leone': np.float64(7017554.51676625), 'Singapore': np.float64(5673053.930198446), 'Sint Maarten (Dutch part)': np.float64(48463.46002221387), 'Slovakia': np.float64(6126428.836429104), 'Slovenia': np.float64(2309878.0437906757), 'Solomon Islands': np.float64(630274.8860930335), 'Somalia': np.float64(13964877.818675995), 'South Africa': np.float64(62406513.43888831), 'South Korea': np.float64(59362566.35335541), 'South Sudan': np.float64(9699977.457404226), 'Spain': np.float64(50484316.819913566), 'Sri Lanka': np.float64(24275299.739944518), 'Sudan': np.float64(41118002.729313016), 'Suriname': np.float64(640781.2740051206), 'Svalbard and Jan Mayen': np.float64(2824.2056960844784), 'Sweden': np.float64(10377023.63436465), 'Switzerland': np.float64(8834585.719220102), 'Syria': np.float64(22345201.734119296), 'Taiwan': np.float64(28472117.831158638), 'Tajikistan': np.float64(9089221.978640795), 'Tanzania': np.float64(52315478.57469332), 'Thailand': np.float64(81031775.03505278), 'Togo': np.float64(7639966.670206994), 'Tokelau': np.float64(1893.247819326175), 'Tonga': np.float64(130219.15890323278), 'Trinidad and Tobago': np.float64(1676388.5286407769), 'Tunisia': np.float64(12469806.524661273), 'Turkey': np.float64(87390021.33112645), 'Turkmenistan': np.float64(6480708.079579636), 'Turks and Caicos Islands': np.float64(37635.5757032932), 'Tuvalu': np.float64(11501.518035847665), 'Uganda': np.float64(37290814.95813501), 'Ukraine': np.float64(54312013.25761765), 'United Arab Emirates': np.float64(7063076.872554123), 'United Kingdom': np.float64(66988583.96748638), 'United States': np.float64(355696937.4301138), 'United States Virgin Islands': np.float64(129967.97131439019), 'Uruguay': np.float64(3818929.2309932783), 'Uzbekistan': np.float64(33307249.89187014), 'Vanuatu': np.float64(265745.9968900038), 'Vatican': np.float64(560.0372239411072), 'Venezuela': np.float64(32384210.048431635), 'Vietnam': np.float64(101602866.21364021), 'Wallis and Futuna': np.float64(14909.991499444674), 'Western Sahara': np.float64(515844.70095180534), 'World': np.float64(8364439726.469025), 'Yemen': np.float64(29931790.077147126), 'Zambia': np.float64(16058352.366371512), 'Zimbabwe': np.float64(15894209.706043959)}

/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/Users/luzhixuan/.pyenv/versions/3.11.0/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [67]:
forecast_df.to_csv('forecast_po.csv',index = False)

In [69]:
df = pd.read_csv('forecast.csv')
dm = pd.read_csv('forecast_cm.csv')
dk = pd.read_csv('forecast_po.csv')
df = pd.merge(df,dm,on = 'Country', how = 'inner')
df = pd.merge(df,dk,on = 'Country', how = 'inner')

In [70]:
df

               Country    Forecast_x    Forecast_y      Forecast
0          Afghanistan  2.521679e-04  8.746110e+06  3.073212e+07
1              Albania  1.984708e-04  6.496579e+06  3.722142e+06
2              Algeria  5.566656e-03  1.530353e+08  4.215797e+07
3              Andorra  6.860872e-06  4.825311e+05  8.759472e+04
4               Angola  1.800848e-03  2.604825e+07  2.638199e+07
..                 ...           ...           ...           ...
208            Vietnam  2.916747e-03  1.682987e+08  1.016029e+08
209  Wallis and Futuna  2.196749e-07  3.064222e+04  1.490999e+04
210              Yemen  6.612605e-04  2.137588e+07  2.993179e+07
211             Zambia  4.171459e-04  4.548142e+06  1.605835e+07
212           Zimbabwe  6.488792e-04  1.494801e+07  1.589421e+07

[213 rows x 4 columns]

In [71]:
df.rename(columns={
    'Forecast_x': 'Temperature Contribution',
    'Forecast_y': 'CO2 Emission',
    'Forecast': 'Population'
}, inplace=True)

# Save the updated DataFrame to a new CSV
df.to_csv('updated_forecast.csv', index=False)

In [72]:
developed_countries = [
    'Australia', 'Austria', 'Belgium', 'Canada', 'Denmark', 'Finland', 'France',
    'Germany', 'Iceland', 'Ireland', 'Israel', 'Italy', 'Japan', 'Luxembourg',
    'Netherlands', 'New Zealand', 'Norway', 'Portugal', 'South Korea', 'Spain',
    'Sweden', 'Switzerland', 'United Kingdom', 'United States'
]

# Add a column to the DataFrame to classify countries
df['Country Classification'] = df['Country'].apply(
    lambda x: 'Developed' if x in developed_countries else 'Developing'
)

# Save the updated DataFrame to a new CSV
df.to_csv('updated_forecast.csv', index=False)